- name: Run NocoDB App
  hosts: app
  become: true
  vars:
    version: latest
    container_name: nocodb
    container_image: nocodb/nocodb
    db_node_host: "{{ groups['db'][0] }}"
    db_connection_string: "pg://{{ groups['db'][0] }}:5432?u=nocodb&p=nocodb&d=nocodb"
    auth_secret: supersecret
    public_url: https://nocodb.example.com
  tasks:    
    - name: Set up data folder
      file:
        path: /home/nocodb
        state: directory
        mode: '0644'

    - name: Pull image
      community.docker.docker_image:
        name: "{{ container_image }}:{{ version }}"
        source: pull

    - name: Run containers
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ container_image }}"
        restart: true
        restart_policy: always
        network_mode: host
        env:
          NC_DB: "{{ db_connection_string }}"
          NC_AUTH_JWT_SECRET: "{{ auth_secret }}"
          #NC_PUBLIC_URL: {{ public_url }}
          #NUXT_PUBLIC_NC_BACKEND_URL: {{ public_url }}
        volumes:
          - /home/nocodb/:/usr/app/data/
        exposed_ports:
          - "8080"
        ports:
          - "8080:8080"
        state: started